# Default target
.PHONY: help
help:
	@echo "$(BLUE)Available commands:$(NC)"
	@echo ""
	@echo "$(GREEN)Ollama Setup:$(NC)"
	@echo "  make setup-ollama    - Install and setup Ollama with Llama2 model"
	@echo "  make restart-ollama  - Restart the Ollama service"
	@echo ""
	@echo "$(GREEN)Simple Chat Application:$(NC)"
	@echo "  make simple-chat-build    - Build all services for the simple chat application"
	@echo "  make simple-chat-start    - Start all services for the simple chat application"
	@echo "  make simple-chat-stop     - Stop all services for the simple chat application"
	@echo "  make simple-chat-restart  - Restart all services for the simple chat application"
	@echo ""
	@echo "$(GREEN)Personal MD Files Application:$(NC)"
	@echo "  make personal-md-files-build    - Build all services for the personal MD files application"
	@echo "  make personal-md-files-start    - Start all services for the personal MD files application"
	@echo "  make personal-md-files-stop     - Stop all services for the personal MD files application"
	@echo "  make personal-md-files-restart  - Restart all services for the personal MD files application"
	@echo ""
	@echo "$(GREEN)Maintenance:$(NC)"
	@echo "  make clean           - Clean up Docker resources (remove unused containers, networks, images)"
	@echo "  make check-docker    - Check if Docker is installed"
	@echo "  make check-docker-compose - Check if Docker Compose is installed"
	@echo ""
	@echo "$(YELLOW)Note:$(NC) All commands require Docker and Docker Compose to be installed."
