version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rag_demo
      MYSQL_USER: rag_user
      MYSQL_PASSWORD: rag_password
    ports:
      - "7011:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "7012:6333"
      - "7013:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mysql_data:
  qdrant_data: